import Layouts from "@/components/Layouts";
import Head from "next/head";
import React from "react";
import AboutSection from "@/components/AboutSection";
// Image imported
// import aboutImg from "@/assets/about.webp";
import { Aboutbred } from "@/components/Aboutbred";
import { Textmonial } from "@/components/Textmonial";
import ImgSection from "@/components/ImgSection";
import ChooseUs from "@/styles/ChooseUs";

/* about page */
const index = () => {
  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layouts>
        <Aboutbred bread={"About Us"} />
        <AboutSection
          data={{
            subTitle: "About Refine Pixel ",
            title: "Upgrade the Imagery Where Art Meets Precision.",
            description:
              "Trust Refine Pixel as your reliable partner in editing services. With our commitment to magnificence, we design images that enchant and inspire.",
            btnName: "Read More",
            btnLink: "/",
            image: "/assets/about.webp",
          }}
        />
        <div className="ped40"></div>
        <ChooseUs />
        <Textmonial />
        <ImgSection />
      </Layouts>
    </>
  );
};

export default index;
