import Layouts from "@/components/Layouts";
import Head from "next/head";
import React from "react";
import AboutSection from "@/components/AboutSection";
// Image imported
// import aboutImg from "@/assets/about.webp";
import { Aboutbred } from "@/components/Aboutbred";
import { Textmonial } from "@/components/Textmonial";
import ImgSection from "@/components/ImgSection";
import ChooseUs from "@/styles/ChooseUs";

/* about page */
const index = () => {
  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layouts>
        <Aboutbred bread={"About Us"} />
        <AboutSection
          data={{
            subTitle: "About Refine Pixel ",
            title: "Upgrade the Imagery Where Art Meets Precision.",
            description:
              "Trust Refine Pixel as your reliable partner in editing services. With our commitment to magnificence, we design images that enchant and inspire.",
            btnName: "Read More",
            btnLink: "/",
            image: "/assets/about.webp",
          }}
        />
        <div className="ped40"></div>
        <ChooseUs data={{ subTitle: "Why Choose Us?", title: "What Makes Us Different?", para: "Discover what sets us apart in the industry - from modern technology to a global approach. At Refine Pixel we redefine editing.", cards: [{ title: "Modern Technology", para: "Our state-of-the-art technology at Refine Pixel enhances and streamlines the editing process. It positions us at the industry's forefront." }, { title: "Global Perspective", para: "We have a client base all over the world. It encourages us to bring diverse and multicultural perspectives to our editing services." }, { title: "Competitive Pricing", para: "We offer our services at the best prices! Without compromising on the quality. We ensure our services are accessible to all, be it an individual or a business." }, { title: "24/7 Customer Support", para: "We offer 24/7 customer support and assistance. We address every client query, no matter when or where you're calling from." }] }} />
        <Textmonial />
        <ImgSection />
      </Layouts>
    </>
  );
};

export default index;
