"use client";
import Layouts from "@/components/Layouts";
import Head from "next/head";
import React, { useState } from "react";
import AboutSection from "@/components/AboutSection";
// Image imported
// import aboutImg from "@/assets/about.webp";
import { Aboutbred } from "@/components/Aboutbred";
import { Textmonial } from "@/components/Textmonial";
import ImgSection from "@/components/ImgSection";
import ChooseUs from "@/styles/ChooseUs";
import { Pricing_card } from "@/components/Pricing_card";

/* about page */
const Index = () => {
  const [activeTab, setActiveTab] = useState(true);

  return (
    <>
      <Head>
        <title>Pricing Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layouts>
        <Aboutbred bread={"Pricing"} />

        <div className="ped40"></div>

        <div className="container titlePrice">
          <div className="content textCenter">
            <h4>Pricing</h4>
            <p>
              Refine Pixel keeps its photo editing pricing policy absolutely
              clear. You can easily calculate the cost of your order using the
              detailed lists below
            </p>
          </div>
        </div>

        <div className="tabBtn_pricing container flex alignCenter justSpaceCenter gap10">
          <button
            className={activeTab ? "active" : ""}
            onClick={() => {
              setActiveTab(true);
            }}
          >
            Regular Prices
          </button>
          <button
            className={activeTab ? "" : "active"}
            onClick={() => {
              setActiveTab(false);
            }}
          >
            Special Offers / Packages
          </button>
        </div>

        <div className="ped20"></div>
        {activeTab ? (<>
          <h4 className="pricingSubHeading">Culling 0.05$ <span>/ per image</span></h4>
          <div className="flex justSpaceBetween gap10">
            {/* <Pricing_card
              title="Culling"
              sub_title="0.05$"
              s_title_span="/ per image"
              btn_value="Order Now"
            /> */}
            <Pricing_card
              title="Color Correction"
              sub_title="0.25$"
              s_title_span="/ per image"
              p="Feature"
              list={["Light Balance", "Tonal Range Enhancement", "Shadow & Highlights management", "Exposure", "Color tone and temperature", "saturation", "contrast enhancement", "vibrancy", "Following up The style of the client", "lightroom adjustments", "Image cropping"]}
              btn_value="Order Now"
            />
            <Pricing_card
              title="Basic Level"
              sub_title="3$"
              s_title_span="/ per image"
              p="Feature"
              list={["Light beauty retouching", "Blemishes scars acne removal", "Teeth whitening", "Skin smoothening", "Image cropping", "color & light correction", "Portraits retouch", "Close-ups", "Studio photos", "Background editing", "newborn retouching"]}
              btn_value="Order Now"
            />
            <Pricing_card
              title="Pro Level"
              sub_title="4$"
              s_title_span="/ per image"
              p="Feature"
              list={["Basic beauty retouching", "Pro beauty correction", "Blemishes scars acne removal", "Teeth whitening", "Skin smoothening", "background enhancement & extending", "Body retouching", "stray hair removal", "face rinkles removal", "Headshots retouching",
                "Background editing", "Portraits retouching"]}
              btn_value="Order Now"
            />
            <Pricing_card
              title="Noir Edits"
              sub_title="4$"
              s_title_span="/ per image"
              p="Feature"
              list={["Black & white", "Light beauty retouching", "Blemishes scars acne removal", "Teeth whitening", "Skin smoothening", "Image cropping", "color & light correction", "Portraits retouch", "Close-ups", "Studio photos", "Background editing", "Liquify tool"]}
              btn_value="Order Now"
            />
            <Pricing_card
              title="Hybrid Edits"
              sub_title="100$"
              s_title_span="/ per image"
              p="Feature"
              list={["Color Correction", "Light beauty retouching", "Blemishes scars acne removal", "Teeth whitening", "Minor distraction removal", "a sky swap", "straightening", "skew fixes", "dodging & burning", "Skin Smoothening", "Image cropping", "Premium toning and a texture overlay", "changing color of Clothes", "braces removal", "HDR effects"]}
              btn_value="Order Now"
            />
          </div>
          <p className="bottomPara">We have monthly subscription plans as detailed but if these do not meet your requirements then we are happy to negotiate a subscription service that is more suitable to your business needs.</p>
        </>
        ) : (
          <>
            <h4 className="pricingSubHeading">Culling 0.035$ <span>/ per image</span></h4>
            <div className="flex justSpaceCenter  gap10 offerArea yearly_package">
              {/* <Pricing_card
              title="Culling"
              sub_title="0.04$ or 0.035$"
              s_title_span="/ per image"
              btn_value="Order Now"
            /> */}
              <Pricing_card
                title="Color Correction"
                sub_title="249$"
                s_title_span="/ per month"
                p="Feature"
                list={["Unlimited Color Correction Events", "Up to 800 color corrected images per event*", "Light Balance", "Tonal Range Enhancement", "Shadow & Highlights management", "Exposure", "Color tone and temperature", "saturation", "contrast enhancement", "vibrancy", "Following up The style of the client", "lightroom adjustments", "Image cropping"]}
                btn_value="Order Now"
                bottomPara={"*15 cents per image over 800"}
              />
              <Pricing_card
                title="Basic Level"
                sub_title="2.5$"
                s_title_span="/ per image"
                p="Feature"
                list={["Light beauty retouching", "Blemishes scars acne removal", "Teeth whitening", "Skin smoothening", "Image cropping", "color & light correction", "Portraits retouch", "Close-ups", "Studio photos", "Background editing", "newborn retouching"]}
                btn_value="Order Now"
              />
              <Pricing_card
                title="Pro Level"
                sub_title="3$"
                s_title_span="/ per image"
                p="Feature"
                list={["Basic beauty retouching", "Pro beauty correction", "Blemishes scars acne removal", "Teeth whitening", "Skin smoothening", "background enhancement & extending", "Body retouching", "stray hair removal", "face wrinkles removal", "Headshots retouching", "Background editing", "Portraits retouching"]}
                btn_value="Order Now"
              />
              <Pricing_card
                title="Noir Edits"
                sub_title="3$"
                s_title_span="/ per image"
                p="Feature"
                list={["Black & white", "Light beauty retouching", "Blemishes scars acne removal", "Teeth whitening", "Skin smoothening", "Image cropping", "color & light correction", "Portraits retouch", "Close-ups", "Studio photos", "Background editing", "Liquify tool"]}
                btn_value="Order Now"
              />
              <Pricing_card
                title="Hybrid Edits"
                sub_title="75$"
                s_title_span="/ per image"
                p="Feature"
                list={["Color Correction", "Light beauty retouching", "Blemishes scars acne removal", "Teeth whitening", "Minor distraction removal", "a sky swap", "straightening", "skew fixes", "dodging & burning", "Skin Smoothening", "Image cropping", "Premium toning and a texture overlay", "changing color of Clothes", "braces removal", "HDR effects"]}
                btn_value="Order Now"
              />
            </div>
            <p className="bottomPara">We have monthly subscription plans as detailed but if these do not meet your requirements then we are happy to negotiate a subscription service that is more suitable to your business needs.</p>
          </>
        )}

        <Textmonial />
        <ImgSection />
      </Layouts>
    </>
  );
};

export default Index;
