import Layouts from "@/components/Layouts";
import Head from "next/head";
import React, { useState } from "react";
import AboutSection from "@/components/AboutSection";
// Image imported
// import aboutImg from "@/assets/about.webp";
import { Aboutbred } from "@/components/Aboutbred";
import { Textmonial } from "@/components/Textmonial";
import ImgSection from "@/components/ImgSection";
import ChooseUs from "@/styles/ChooseUs";
import { Pricing_card } from "@/components/Pricing_card";

/* about page */
const index = () => {
  const [activeTab, setActiveTab] = useState(true);

  return (
    <>
      <Head>
        <title>Pricing Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layouts>
        <Aboutbred bread={"Pricing"} />

        <div className="ped40"></div>

        <div className="container titlePrice">
          <div className="content textCenter">
            <h4>Pricing</h4>
            <p>
              Weedit.Photos keeps its photo editing pricing policy absolutely
              clear. You can easily calculate the cost of your order using the
              detailed lists below
            </p>
          </div>
        </div>

        <div className="tabBtn_pricing container flex alignCenter justSpaceCenter gap10">
          <button
            className={activeTab ? "active" : ""}
            onClick={() => {
              setActiveTab(true);
            }}
          >
            Regular Prices
          </button>
          <button
            className={activeTab ? "" : "active"}
            onClick={() => {
              setActiveTab(false);
            }}
          >
            Special Offers / Packages
          </button>
        </div>

        <div className="ped20"></div>
        {activeTab ? (
          <div className="container flex justSpaceBetween gap10">
            <Pricing_card
              title="Culling"
              sub_title="0.06 USD"
              s_title_span="/ per image"
              p="Services Applied:"
              list={[
                "Light Balance",
                "Light Balance",
                "Light Balance",
                "Light Balance",
                "Light Balance",
              ]}
              btn_value="Order"
            />
            <Pricing_card
              title="Culling"
              sub_title="0.06 USD"
              s_title_span="/ per image"
              p="Services Applied:"
              list={["Light Balance", "Light Balance", "Light Balance"]}
              btn_value="Order"
            />
            <Pricing_card
              title="Culling"
              sub_title="0.06 USD"
              s_title_span="/ per image"
              p="Services Applied:"
              list={["Light Balance", "Light Balance", "Light Balance"]}
              btn_value="Order"
            />
            <Pricing_card
              title="Culling"
              sub_title="0.06 USD"
              s_title_span="/ per image"
              p="Services Applied:"
              list={["Light Balance", "Light Balance", "Light Balance"]}
              btn_value="Order"
            />
            <Pricing_card
              title="Culling"
              sub_title="0.06 USD"
              s_title_span="/ per image"
              p="Services Applied:"
              list={["Light Balance", "Light Balance", "Light Balance"]}
              btn_value="Order"
            />
          </div>
        ) : (
          <div className="container flex justSpaceCenter  gap10 offerArea yearly_package">
            <Pricing_card
              title="Culling"
              sub_title="0.06 USD"
              s_title_span="/ per image"
              p="Services Applied:"
              list={["Light Balance", "Light Balance", "Light Balance"]}
              btn_value="Order"
            />
            <Pricing_card
              title="Culling"
              sub_title="0.06 USD"
              s_title_span="/ per image"
              p="Services Applied:"
              list={[
                "Light Balance",
                "Light Balance",
                "Light Balance",
                "Light Balance",
                "Light Balance",
              ]}
              btn_value="Order"
            />
          </div>
        )}

        <Textmonial />
        <ImgSection />
      </Layouts>
    </>
  );
};

export default index;
