import React from "react";
import Head from "next/head";
import { Aboutbred } from "@/components/Aboutbred";
import Layouts from "@/components/Layouts";
import Service1 from "@/components/Service1";
import VideoSec from "@/components/VideoSec";
import Thirdservisec from "@/components/Thirdservisec";
import ReactCompareImage from "react-compare-image";
import Faq from "@/components/Faq";
import Cta from "@/components/Cta";

const WebDesignAndDevelopement = () => {
  const data = [
    {
      title: "What Is Included With Color Correction Services?",
      Description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
    {
      title: "What Is Included With Color Correction Services?",
      Description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
    {
      title: "What Is Included With Color Correction Services?",
      Description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
  ];
  const data_1 = [
    {
      title: "What Is Included With Color Correction Services?",
      Description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
    {
      title: "What Is Included With Color Correction Services?",
      Description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
    {
      title: "What Is Included With Color Correction Services?",
      Description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
  ];

  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layouts>
        <Aboutbred bread={"Web Design and Developement"} />
        <div className="ped40"></div>
        <Service1 data={{ imageDir: true, button: true, subTitle: "Web design and development", btnText: "Buy Now​ Call Today​", title: "Crafting and Revamping Websites for Maximum Impact!", paraArray: ["Embark on a journey of digital transformation as we meticulously craft and revamp websites to unleash their full potential for maximum impact. Our expert team combines cutting-edge design techniques with strategic insights to ensure your website not only looks stunning but also drives results", "From enhancing user experience to optimizing for search engines, we tailor our approach to meet your specific goals and objectives. Whether you're launching a new site or giving your current one a makeover, trust us to elevate your online presence and leave a lasting impression on your audience."] }} />
        <Service1 data={{ imageDir: false, button: true, subTitle: "Web design and development", btnText: "Buy Now​ Call Today​", title: "Cutting-Edge HTML5 Website Development Solutions", paraArray: ["Step into the future of web development with our cutting-edge HTML5 solutions. From sleek designs to seamless functionality, we craft websites that not only impress but also engage your audience. Harnessing the latest advancements in HTML5 technology, we ensure your site is optimized for performance, accessibility, and scalability across all devices.", "Whether you're launching a new website or upgrading an existing one, our expert team is committed to delivering a tailored solution that sets you apart from the competition and drives results"] }} />

        <Thirdservisec data={{subTitle: "Web design and development", title: "Expertly Crafted Duda Platform Designs: Transform Your Website Experience", paraArray: ["Embark on a journey of digital transformation with our expertly crafted Duda platform designs. We specialize in creating stunning websites that not only showcase your brand but also provide an exceptional user experience. Our team combines creativity with technical expertise to tailor every aspect of your website to your unique needs and goals", "From sleek and modern designs to seamless functionality across all devices, we ensure that your website stands out from the crowd and leaves a lasting impression on your visitors. Let us help you elevate your online presence and take your website to the next level with our Duda platform design solutions"] }}/>
        {/* <Service1 data={{ imageDir: true, button: true, subTitle: "Web design and development", btnText: "Buy Now​ Call Today​", title: "Expertly Crafted Duda Platform Designs: Transform Your Website Experience", paraArray: ["Embark on a journey of digital transformation with our expertly crafted Duda platform designs. We specialize in creating stunning websites that not only showcase your brand but also provide an exceptional user experience. Our team combines creativity with technical expertise to tailor every aspect of your website to your unique needs and goals", "From sleek and modern designs to seamless functionality across all devices, we ensure that your website stands out from the crowd and leaves a lasting impression on your visitors. Let us help you elevate your online presence and take your website to the next level with our Duda platform design solutions"] }} /> */}
        <Service1 data={{ imageDir: false, button: true, subTitle: "Web design and development", btnText: "Buy Now​ Call Today​", title: "Transforming UX: Professional Design Services Tailored for Users", paraArray: ["Embark on a journey of user-centric design transformation with our professional services, meticulously crafted to elevate the user experience (UX) and drive meaningful engagement.", "From intuitive interfaces to seamless interactions, we prioritize user needs and preferences to create designs that delight and inspire. Our expert team combines creativity with strategic thinking to ensure every aspect of your digital experience is tailored to enhance usability, accessibility, and overall satisfaction. Whether you're launching a new product or revamping an existing platform, trust us to deliver designs that exceed expectations and leave a lasting impression on your users."] }} />
        <VideoSec />
        <Service1 data={{ imageDir: true, button: true, subTitle: "Web design and development", btnText: "Buy Now​ Call Today​", title: "Revamp Your Online Presence: Bespoke E-Commerce Solutions", paraArray: ["Embark on a journey to redefine your online presence with our bespoke e-commerce solutions. We specialize in crafting tailored strategies that breathe new life into your brand, enhancing its visibility and driving sales", "From seamless user experiences to personalized shopping journeys, we prioritize every detail to ensure maximum engagement and conversion. Whether you're a startup looking to establish your digital footprint or an established brand seeking to revamp your e-commerce platform, our expert team is here to turn your vision into reality and propel your business to new heights in the online marketplace"] }} />
        <Service1 data={{ imageDir: false, button: true, subTitle: "Web design and development", btnText: "Buy Now​ Call Today​", title: "Round-the-Clock Assistance & Care: We've Got You Covered!", paraArray: ["Experience unparalleled support and care with our round-the-clock assistance services. We're dedicated to ensuring your needs are met at any time of day or night, offering prompt and reliable assistance whenever you require it", "Whether you have questions, concerns, or need help resolving issues, our expert team is always ready to provide the support you need. With us, you can rest assured that you're in good hands, knowing that we've got you covered around the clock"] }} />
        {/* <div className="ped40"></div> */}

        <section className="Thirdservice samplework">
          <div className="container">
            <div className="flex gap">
              <div className="col50">
                {" "}
                <ReactCompareImage
                  leftImage={"/assets/after.webp"}
                  rightImage={"/assets/before.webp"}
                />
              </div>
              <div className="col50">
                {" "}
                <ReactCompareImage
                  leftImage={"/assets/after.webp"}
                  rightImage={"/assets/before.webp"}
                />
              </div>
            </div>
          </div>
        </section>
        {/* <section className="samplework1">
          <div className="container">
            <ReactCompareImage
              leftImage={"/assets/after.webp"}
              rightImage={"/assets/before.webp"}
            />
          </div>
        </section> */}

        <Faq data={data} data_1={data_1} />

        <Cta />

      </Layouts>
    </>
  );
};

export default WebDesignAndDevelopement;
