import React from "react";
import Head from "next/head";
import { Aboutbred } from "@/components/Aboutbred";
import Layouts from "@/components/Layouts";
import Service1 from "@/components/Service1";
import VideoSec from "@/components/VideoSec";
import Workimgedit from "@/components/Workimgedit";
import Videoedit from "@/components/Videoedit";

const gallery = () => {
  return (
    <>
      <Head>
        <title>Our Work</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layouts>
        <Aboutbred bread={"Our Work"} />
        <Workimgedit/>
        <Videoedit/>
      </Layouts>
    </>
  );
};

export default gallery;
