import React from "react";
import Head from "next/head";
import { Aboutbred } from "@/components/Aboutbred";
import Layouts from "@/components/Layouts";
import Service1 from "@/components/Service1";
import VideoSec from "@/components/VideoSec";
import Thirdservisec from "@/components/Thirdservisec";
import ReactCompareImage from "react-compare-image";
import Faq from "@/components/Faq";
import Cta from "@/components/Cta";

const Imagesediting = () => {
  const data = [
    {
      title: "Why Choose Refine Pixel?",
      Description: "Our team is dedicated to the success of each photographer we work with. We offer a custom process with every order. This ensures that each image or design that our client receives is true to their studio and their style.",
    },
    {
      title: "What Is Your Minimum Order?",
      Description: "For Standard Evolve accounts there is a $30 USD minimum.For Premier Members, there is no order minimum.",
    },
    {
      title: "What Is Standard Turn Around Time?",
      Description: "Typically, you can expect your order returned in 5 business days or less. If you are in need of a quicker turn around, you can add a rush to your order.Select the Same Day rush for a 1 business day turnaround, Next Day rush for a 2 business day turnaround.",
    },
  ];
  const data_1 = [
    {
      title: "What If I’m Not Happy With My Completed Order?",
      Description: "We completely guarantee our work. So, if you are not happy with the job, let us know it needs to be revisited. Please do not edit it yourself, that’s what we are here for!Click the survey link at the bottom of your Order Complete email: GIVE US FEEDBACK ON THIS JOB.",
    },
    {
      title: "Can I Work With One Editor?",
      Description: "We assign each client 2-3 editors. If one editor is out, you’ll still be well taken care of by someone who is familiar with your style and workflow.",
    },
    {
      title: "What Version Of Lightroom Do You Accept?",
      Description: "We are currently accepting the latest version of Lightroom Classic.If working in an older version including Lightroom 5 or 6/CC 2015 we recommend upgrading to Lightroom Classic via the Adobe Creative Cloud.",
    },
  ];

  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layouts>
        <Aboutbred bread={"Images Editing"} />
        <div className="ped40"></div>
        <Service1 data={{
          imageDir: false, mainImgPath: "/assets/before.jpg", button: true, btnLink: "/contact", subTitle: "Colour correction", title: "Color Magic: Brighten Your Images with Refine Pixel.", btnText: "Buy Now​ Call Today​", paraArray: ["We also offer hybrid editing services at competitive prices! Our designers and editors merge various editing styles to create visually unique images.", "We create images using our best elements and expertise.Our approach includes blending lively colors with modern compositions or interesting textures.", " We guarantee to deliver a classic charm and one-of-a-kind visual experience. So, enhance your images with our hybrid edits. "],
          subImagesTitle: "Color Correction", subImagesArray: [
            {
              aftimg: "./assets/ColourCorrection/3_a.jpg",
              befimg: "./assets/ColourCorrection/3_b.jpg",
            },
            {
              aftimg: "./assets/ColourCorrection/4_a.jpg",
              befimg: "./assets/ColourCorrection/4_b.jpg",
            },
            {
              aftimg: "./assets/ColourCorrection/5_a.jpg",
              befimg: "./assets/ColourCorrection/5_b.jpg",
            },
            {
              aftimg: "./assets/ColourCorrection/6_a.jpg",
              befimg: "./assets/ColourCorrection/6_b.jpg",
            }, {
              aftimg: "./assets/ColourCorrection/7_a.jpg",
              befimg: "./assets/ColourCorrection/7_b.jpg",
            },
          ]
        }} />
        <Service1 data={{
          imageDir: true, mainImgPath: "/assets/culling/culling-img.jpg", button: true, btnLink: "/contact", subTitle: "Culling", title: "Sharp Cut: Image Culling & Selection", btnText: "Buy Now​ Call Today​", paraArray: ["Cut through the clutter effortlessly! At Refine Pixel, our image culling & selection service simplifies your picture-picking process.", "Our skilled team meticulously analyzes each image, eliminating blurriness, duplicates, and unflattering angles. What's left? A refined selection of your best shots, saving you time and effort.", "Let us handle the heavy lifting while you enjoy a streamlined selection process!"],
          subImagesTitle: "Culling", subImagesArray: [
            {
              aftimg: "./assets/newbornbaby/1_a.jpg",
              befimg: "./assets/newbornbaby/1_b.jpg",
            },
            {
              aftimg: "./assets/newbornbaby/8_a.jpg",
              befimg: "./assets/newbornbaby/8_b.jpg",
            },
            {
              aftimg: "./assets/newbornbaby/3_a.jpg",
              befimg: "./assets/newbornbaby/3_b.jpg",
            },
            {
              aftimg: "./assets/newbornbaby/5_a.jpg",
              befimg: "./assets/newbornbaby/5_b.jpg",
            }, {
              aftimg: "./assets/newbornbaby/4_a.jpg",
              befimg: "./assets/newbornbaby/4_b.jpg",
            },
          ]
        }} />
        <Service1 data={{
          imageDir: false, mainImgPath: "./assets/retouching/removeChangingBackground/main-img.jpg", button: true, btnLink: "/contact", subTitle: "Retouching", title: "Refine Pixel: Elevating Your Visuals to Perfection", btnText: "Buy Now​ Call Today​", paraArray: ["Refine Pixel specialises in comprehensive image retouching services, ensuring your photographs reach their full potential. From portrait retouching to background changes, body sculpting, high-end retouching, nude photo enhancements, and newborn baby retouching, we offer a diverse range of solutions tailored to your needs. ", "Whether refining physique or preserving natural beauty, we transform ordinary photos into extraordinary pieces of art. Trust us for professional and discreet retouching services that capture the essence of each moment perfectly."],
          subImagesTitle: "Retouching", subImagesArray: [
            {
              aftimg: "./assets/retouching/removeChangingBackground/2_a.jpg",
              befimg: "./assets/retouching/removeChangingBackground/2_b.jpg",
            },
            {
              aftimg: "./assets/retouching/removeChangingBackground/3_a.jpg",
              befimg: "./assets/retouching/removeChangingBackground/3_b.jpg",
            },
            {
              aftimg: "./assets/newbornbaby/1_a.jpg",
              befimg: "./assets/newbornbaby/1_b.jpg",
            },
            {
              aftimg: "./assets/RealEstate/3_a.jpg",
              befimg: "./assets/RealEstate/3_b.jpg",
            },
          ]
        }} />
        <Service1 data={{
          imageDir: true, mainImgPath: "/assets/RealEstate/main-img.jpg", button: true, btnLink: "/contact", subTitle: " Real-estate Editing", title: "Pixel Perfect: Real Estate Editing Expertise", btnText: "Buy Now​ Call Today​", paraArray: ["Make your property pop with our simple and quirky real estate editing service! At Refine Pixel, we take your ordinary photos and turn them into eye-catching showcases.", "Our experts enhance lighting, colors, and composition to create captivating images that stand out in the market. From beautiful panoramas to enticing close-ups, we ensure your listings catch the eye of potential buyers.", " Let us work our magic on your real estate photos and watch as your property sells itself!"],
          subImagesTitle: "Real Estate", subImagesArray: [
            {
              aftimg: "./assets/RealEstate/1_a.jpg",
              befimg: "./assets/RealEstate/1_b.jpg",
            },
            {
              aftimg: "./assets/RealEstate/2_a.jpg",
              befimg: "./assets/RealEstate/2_b.jpg",
            },
            {
              aftimg: "./assets/RealEstate/3_a.jpg",
              befimg: "./assets/RealEstate/3_b.jpg",
            },
            {
              aftimg: "./assets/RealEstate/4_a.jpg",
              befimg: "./assets/RealEstate/4_b.jpg",
            },
            {
              aftimg: "./assets/RealEstate/5_a.jpg",
              befimg: "./assets/RealEstate/5_b.jpg",
            }
          ]
        }} />
        <Thirdservisec data={{
          subTitle: "Product Photo Editing", btnLink: "/contact", title: "Picture-Perfect Transformation by Refine Pixel!", paraArray: ["With Refine Pixel's Product Photo Editing, take center stage. We meticulously polish each element, turning your images into an impressive exhibition of quality", "Let us enhance your photos' allure."],
          subImagesTitle: "New Born Baby", subImagesArray: [
            {
              aftimg: "./assets/product/10_a.jpg",
              befimg: "./assets/product/10_b.jpg",
            },
            {
              aftimg: "./assets/product/11_a.jpg",
              befimg: "./assets/product/11_b.jpg",
            },
            {
              aftimg: "./assets/product/12_a.jpg",
              befimg: "./assets/product/13_b.jpg",
            },
            {
              aftimg: "./assets/product/13_a.jpg",
              befimg: "./assets/product/13_b.jpg",
            },]
        }} />
        <Service1 data={{
          imageDir: false, mainImgPath: "/assets/newbornbaby/main-img.jpg", button: true, btnLink: "/contact", subTitle: "New Born baby", title: "Tiny Tweak: Newborn Baby Editing", btnText: "Buy Now​ Call Today​", paraArray: ["Welcome your bundle of joy with picture-perfect perfection! Our newborn baby editing service at Refine pixel ensures every precious moment is captured flawlessly.", "From softening skin tones to enhancing those adorable little features, our expert editors delicately craft each image to perfection.", "Preserve those precious memories with a touch of magic, leaving you with heart-melting snapshots to cherish forever. Let us sprinkle some stardust on your newborn photos!"],
          subImagesTitle: "New Born Baby", subImagesArray: [
            {
              aftimg: "./assets/newbornbaby/1_a.jpg",
              befimg: "./assets/newbornbaby/1_b.jpg",
            },
            {
              aftimg: "./assets/newbornbaby/8_a.jpg",
              befimg: "./assets/newbornbaby/8_b.jpg",
            },
            {
              aftimg: "./assets/newbornbaby/3_a.jpg",
              befimg: "./assets/newbornbaby/3_b.jpg",
            },
            {
              aftimg: "./assets/newbornbaby/5_a.jpg",
              befimg: "./assets/newbornbaby/5_b.jpg",
            }, {
              aftimg: "./assets/newbornbaby/4_a.jpg",
              befimg: "./assets/newbornbaby/4_b.jpg",
            },
          ]
        }} />
        <Service1 data={{
          imageDir: true, mainImgPath: "/assets/before.jpg", button: true, btnLink: "/contact", subTitle: "Boudoir", title: "Refine Pixel Boudoir: Where Magic Meets Photography", btnText: "Buy Now​ Call Today​", paraArray: ["Get ready to wow with our special boudoir editing service at Refine pixel! We're here to make your intimate photos even more amazing.", "Our team knows just how to enhance your natural beauty, making sure every detail looks perfect. From smoothing skin to brightening colors, we'll give your photos that extra sparkle.", "Let us work our magic on your boudoir shots, creating stunning images that capture your unique charm!"],
          subImagesTitle: "Color Correction", subImagesArray: [
            {
              aftimg: "./assets/ColourCorrection/3_a.jpg",
              befimg: "./assets/ColourCorrection/3_b.jpg",
            },
            {
              aftimg: "./assets/ColourCorrection/4_a.jpg",
              befimg: "./assets/ColourCorrection/4_b.jpg",
            },
            {
              aftimg: "./assets/ColourCorrection/5_a.jpg",
              befimg: "./assets/ColourCorrection/5_b.jpg",
            },
            {
              aftimg: "./assets/ColourCorrection/6_a.jpg",
              befimg: "./assets/ColourCorrection/6_b.jpg",
            }, {
              aftimg: "./assets/ColourCorrection/7_a.jpg",
              befimg: "./assets/ColourCorrection/7_b.jpg",
            },
          ]
        }} />
        <div className="ped40"></div>

        <section className="Thirdservice samplework">
          <div className="container">
            <div className="flex gap">
              <div className="col50">
                {" "}
                <ReactCompareImage
                  leftImage={"./assets/ColourCorrection/16_a.jpg"}
                  rightImage={"./assets/ColourCorrection/16_b.jpg"}
                />
              </div>
              <div className="col50">
                {" "}
                <ReactCompareImage
                  leftImage={"./assets/ColourCorrection/14_a.jpg"}
                  rightImage={"./assets/ColourCorrection/14_b.jpg"}
                />
              </div>
            </div>
          </div>
        </section>

        <Faq data={data} data_1={data_1} />

        <Cta />

      </Layouts>
    </>
  );
};

export default Imagesediting;
