import React from "react";
import Head from "next/head";
import { Aboutbred } from "@/components/Aboutbred";
import Layouts from "@/components/Layouts";
import Service1 from "@/components/Service1";
import VideoSec from "@/components/VideoSec";
import Thirdservisec from "@/components/Thirdservisec";
import ReactCompareImage from "react-compare-image";
import Faq from "@/components/Faq";
import Cta from "@/components/Cta";

const product_photo_editing = () => {
  const data = [
    {
      title: "What Is Included With Color Correction Services?",
      Description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
    {
      title: "What Is Included With Color Correction Services?",
      Description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
    {
      title: "What Is Included With Color Correction Services?",
      Description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
  ];
  const data_1 = [
    {
      title: "What Is Included With Color Correction Services?",
      Description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
    {
      title: "What Is Included With Color Correction Services?",
      Description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
    {
      title: "What Is Included With Color Correction Services?",
      Description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
  ];

  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layouts>
        <Aboutbred bread={"Retouching"} />
        <div className="ped40"></div>
        <Service1 data={{ imageDir: true, button: true, title: "E-commerce", btnText: "Buy Now​ Call Today​", paraArray: ["Today, selling products on E-commerce websites is a tough task. One must have visually appealing products to catch the buyer's attention. At Refine Pixel, we transform your product pictures into attractive visual assets.", "We can enhance every detail and remove background, we do whatever it takes to make your product shine. Our expert creative team promises to deliver product images that will not only captivate but convert into sales. Hire us to give your business the competitive edge it needs with our E-commerce product photo editing services."] }} />
        <Service1 data={{ imageDir: false, button: true, title: "Background Replacement", btnText: "Buy Now​ Call Today​", paraArray: ["Contact us for background replacement services and watch how we can transform your image from ordinary to extraordinary! Transforming the background is one of the easiest ways to elevate any image. But, it's not a piece of cake, it needs professionals like us to do it skillfully.", "So, no matter whether you're revamping your personal photos or product images, trust the experts at Refine Pixel. Embrace the fresh visual narrative with our background replacement services at the best prices today!"] }} />

        <Thirdservisec />
        <Service1 data={{ imageDir: true, button: true, title: "Transparent Background", btnText: "Buy Now​ Call Today​", paraArray: ["Clarity meets creativity at Refine Pixels transparent background editing services! Unlock the true potential of your pictures with our experts. They have years of experience in transparent background editing.", "Trust us to remove backgrounds seamlessly, be it product photos or profile pictures. With our transparent background editing services, embrace the magic of transparency. Because sometimes when it comes to photographs, simplicity speaks volumes."] }} />
        <Service1 data={{ imageDir: false, button: true, title: "Ghost Mannequin", btnText: "Buy Now​ Call Today​",paraArray:['The ghost mannequin has become trendy because it lets the clothing take center stage! If fashion photography is your forte, ours is ghost mannequin editing services. We are experts in removing the mannequins while creating lifelike silhouettes for the garments.',"We ensure everything is visually clean and there are no distractions from the garments. Trust us to bring life to your fashion photography. Allow us to give the styling the spotlight it deserves."] }} />
        <VideoSec />
        <Service1 data={{ imageDir: true, button:true, title: "Resizing & Cropping", btnText: "Buy Now​ Call Today​",paraArray:["Use our professional resizing and cropping services to enhance your images for any platform. Our expert crew edits each element to make your photos stand out. Refine Pixel is the company you can trust when optimizing your photos for print, online, or social media.","With our resizing and cropping editing services, unleash the full potential of your images. At Refine Pixel, every sized pixel is the source of brilliance! Contact us for our resizing and cropping services today."] }} />
        <Service1 data={{ imageDir: false, button:true, title: "Shadows Adding", btnText: "Buy Now​ Call Today​" ,paraArray:["When we seamlessly place shadows, it can add realism and visual appeal to the images. Our knowledgeable staff at Refine Pixel guarantees smooth integration. We give your graphics a refined touch. You can rely on us for perfect shadows to pictures, be it artistic projects or product shots.","With our Shadows Adding editing service, you may discover the power of depth and dimension. We believe that every image demands to leave a lasting impression. Contact us today for professional shadow-adding services."]}} /> 
        <Service1 data={{ imageDir: false, button:true, title: "Removing Reflection", btnText: "Buy Now​ Call Today​" ,paraArray:["Sometimes unwanted elements such as reflections can ruin the whole image. But, with our removing reflection editing services we can help restore clarity. Our team ensures delivering a crystal clear view of your images through our editing touch.","Removing any distraction allows the main subject to shine. So, whether you need reflection removing services for product or personal shots, contact Refine Pixel today. Embrace the reflection-free art with our expert services at competitive prices."]}} /> 
        <Service1 data={{ imageDir: false, button:true, title: "Clean Up & Retouching", btnText: "Buy Now​ Call Today​" ,paraArray:["Sometimes even the most professionally clicked images need cleanup and retouching. So, contact Refine Pixel for clean & retouching editing services to ensure overall aesthetic. We effortlessly clean up any imperfections.","Refine Pixel can help you in improving the quality of your photos, whether they are self-portraits or images of products. Experience the ultimate transformative power of Clean Up & Retouching service. It is where perfection meets every pixel!"]}} /> 
        <Service1 data={{ imageDir: false, button:true, title: "Adding Watermark", btnText: "Buy Now​ Call Today​" ,paraArray:["Adding watermarks is a professional way to protect your artwork. So, if you need watermark-adding services, Refine Pixel is at your service! We design our watermarks and place them in a way that doesn't disturb your hard work.","Whether you need it for branding or security purposes, we ensure our watermark isn't diverting attention from your content. Refine Pixel's watermarks add a statement to your photographs. Contact us for watermark-adding services because your image deserves style and security."]}} /> 
        <div className="ped40"></div>

        <section className="Thirdservice samplework">
          <div className="container">
            <div className="flex gap">
              <div className="col50">
                {" "}
                <ReactCompareImage
                  leftImage={"/assets/after.webp"}
                  rightImage={"/assets/before.webp"}
                />
              </div>
              <div className="col50">
                {" "}
                <ReactCompareImage
                  leftImage={"/assets/after.webp"}
                  rightImage={"/assets/before.webp"}
                />
              </div>
            </div>
          </div>
        </section>
        {/* <section className="samplework1">
          <div className="container">
            <ReactCompareImage
              leftImage={"/assets/after.webp"}
              rightImage={"/assets/before.webp"}
            />
          </div>
        </section> */}

        <Faq data={data} data_1={data_1} />

        <Cta />

      </Layouts>
    </>
  );
};

export default product_photo_editing;
