import React from "react";
import Head from "next/head";
import { Aboutbred } from "@/components/Aboutbred";
import Layouts from "@/components/Layouts";
import Service1 from "@/components/Service1";
import VideoSec from "@/components/VideoSec";
import Thirdservisec from "@/components/Thirdservisec";
import ReactCompareImage from "react-compare-image";
import Faq from "@/components/Faq";
import Cta from "@/components/Cta";

const Retouching = () => {
  const data = [
    {
      title: "What Is Included With Color Correction Services?",
      Description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
    {
      title: "What Is Included With Color Correction Services?",
      Description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
    {
      title: "What Is Included With Color Correction Services?",
      Description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
  ];
  const data_1 = [
    {
      title: "What Is Included With Color Correction Services?",
      Description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
    {
      title: "What Is Included With Color Correction Services?",
      Description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
    {
      title: "What Is Included With Color Correction Services?",
      Description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
  ];

  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layouts>
        <Aboutbred bread={"Retouching"} />
        <div className="ped40"></div>
        <Service1 data={{ imageDir: true, button: true, title: "Portrait", btnText: "Buy Now​ Call Today​", paraArray: ["With portrait retouching at Refine Pixel, we can make them come to life. Our experienced and skilled editors can enhance your portraits, making sure every detail is perfect. From removing blemishes to softening skin tones, we do everything.", "We specialize in designing portraits that capture the essence of the moment flawlessly. You can trust us with your images to create magnificent portraits. We promise to make masterpieces with every retouch."] }} />
        <Service1 data={{ imageDir: false, button: true, title: "Removing Changing Backgrounds", btnText: "Buy Now​ Call Today​", paraArray: ["At Refine Pixel, unleash the magic of removing changing backgrounds! We are experts in eliminating and changing backgrounds. Allow us to transform the ordinary into an extraordinary piece of art.", "Whether your image requires a whimsical scene or a professional background, we can do both. Let your imagination guide us while we give your photo canvas a brand-new look. Choose us for professional background removing or changing alchemy today! "] }} />

        <Thirdservisec />
        <Service1 data={{ imageDir: true, button: true, title: "Body Retouching", btnText: "Buy Now​ Call Today​", paraArray: ["Sometimes photographs cannot capture the real beauty. Professionals like us need to enhance it using body retouching services. We at Refine Pixel enhance natural contours and sculpt and refine physique.", "We ensure the image is looking its absolute best. We can do everything from minor to transformative adjustments. Step into our world where we craft each curve while celebrating individuality. Contact us for body retouching services today."] }} />
        <Service1 data={{ imageDir: false, button: true, title: "High-end Retouching", btnText: "Buy Now​ Call Today​",paraArray:['Achieve visual perfection with our high-end retouching services. We meticulously enhance every detail in an image that you can "picture perfect." Our experts have a keen eye to find out the finest nuances and give it a flawless finish.',"Our precision and artistry are setting up new benchmarks in the industry. If you wish to refine your visuals with Refine Pixel, contact us today. Experience the epitome of high-end retouching services only with Refine Pixel."] }} />
        <VideoSec />
        <Service1 data={{ imageDir: true, button:true, title: "Nude Photo Retouching", btnText: "Buy Now​ Call Today​",paraArray:["At Refine Pixel, experience the tasteful elegance of nude photo retouching services. We approach every picture with expertise and sensitivity. We make sure to improve the natural beauty while preserving the creative idea behind the photo.","Whether you need complete adjustments or subtle refinements, we ensure the final result is exactly what you want. Both respectful and striking! Trust us for professional and discreet nude photo retouching services. We promise to deliver nothing but inherent human beauty images."] }} />
        <Service1 data={{ imageDir: false, button:true, title: "Newborn Baby Retouching", btnText: "Buy Now​ Call Today​" ,paraArray:["Want to capture the innocence of your newborn baby in a picture forever? Contact Refine Pixel for newborn baby retouching services. We ensure capturing the purity of the precious moments in enhanced pictures.","Trust us, and we will deliver tender and timeless memories through images. We promise each picture to be as captivating as your new bundle of joy. Cherish your new moments while making them last with Refine Pixel today."]}} /> 
        <div className="ped40"></div>

        <section className="Thirdservice samplework">
          <div className="container">
            <div className="flex gap">
              <div className="col50">
                {" "}
                <ReactCompareImage
                  leftImage={"/assets/after.webp"}
                  rightImage={"/assets/before.webp"}
                />
              </div>
              <div className="col50">
                {" "}
                <ReactCompareImage
                  leftImage={"/assets/after.webp"}
                  rightImage={"/assets/before.webp"}
                />
              </div>
            </div>
          </div>
        </section>
        {/* <section className="samplework1">
          <div className="container">
            <ReactCompareImage
              leftImage={"/assets/after.webp"}
              rightImage={"/assets/before.webp"}
            />
          </div>
        </section> */}

        <Faq data={data} data_1={data_1} />

        <Cta />

      </Layouts>
    </>
  );
};

export default Retouching;
