import React from "react";
import Head from "next/head";
import { Aboutbred } from "@/components/Aboutbred";
import Layouts from "@/components/Layouts";
import Service1 from "@/components/Service1";
import VideoSec from "@/components/VideoSec";
import Thirdservisec from "@/components/Thirdservisec";
import ReactCompareImage from "react-compare-image";
import Faq from "@/components/Faq";
import Cta from "@/components/Cta";

const Video_edit = () => {
  const data = [
    {
      title: "What Is Included With Color Correction Services?",
      Description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
    {
      title: "What Is Included With Color Correction Services?",
      Description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
    {
      title: "What Is Included With Color Correction Services?",
      Description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
  ];
  const data_1 = [
    {
      title: "What Is Included With Color Correction Services?",
      Description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
    {
      title: "What Is Included With Color Correction Services?",
      Description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
    {
      title: "What Is Included With Color Correction Services?",
      Description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
  ];

  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layouts>
        <Aboutbred bread={"Video Editing"} />
        <div className="ped40"></div>
        <Service1 data={{ imageDir: true, button: true, subTitle: "Colour correction", btnText: "Buy Now​ Call Today​", title: "Enhance Your Visibility with SEO Strategies for Improved Rankings", paraArray: ["Boost your online visibility and climb the rankings with Weeb Innovation's cutting-edge SEO strategies!Our tailored SEO solutions are designed to elevate your website's visibility, driving more organic traffic and improving your search engine rankings. Through comprehensive keyword research, on-page optimization, and strategic link building, we help your brand rise above the competition and attract the right audience.", "With a data-driven approach and a focus on continual optimization, we ensure that your website not only ranks higher but also delivers a seamless user experience. Let us empower your brand with effective SEO strategies and unlock new opportunities for growth and success online."] }} />
        <Service1 data={{ imageDir: false, button: true, subTitle: "Culling", btnText: "Buy Now​ Call Today​", title: "Smartly Amplify Online Presence with SEM Magic!", paraArray: ["Maximize your online presence and achieve remarkable results with Weeb Innovation's SEM Magic!Our SEM (Search Engine Marketing) strategies are designed to smartly amplify your brand's visibility across search engines, driving targeted traffic to your website and generating leads and conversions. Through strategic keyword targeting, compelling ad copy, and precise audience targeting, we ensure that your ads reach the right audience at the right time.", "With our expertise in SEM, we help you stay ahead of the competition and achieve your business goals efficiently. Let us work our SEM Magic to propel your brand to new heights and unlock the full potential of online advertising."] }} />

        <Thirdservisec />
        <Service1 data={{ imageDir: true, button: true, subTitle: "Signature Edit", btnText: "Buy Now​ Call Today​", title: "Ace Your Web Game with Success-Driven Strategies!", paraArray: ["Level up your online presence and dominate the digital arena with success-driven strategies from Weeb Innovation!Our comprehensive approach combines cutting-edge techniques with strategic insights to help you ace your web game. Whether it's optimizing your website for maximum visibility, crafting compelling content that resonates with your audience, or leveraging the power of social media to engage with your customers, we've got you covered.", "With our tailored strategies and unwavering commitment to your success, we'll help you stand out from the competition and achieve your business goals. Let's work together to elevate your brand and drive meaningful results online."] }} />
        <Service1 data={{
          imageDir: false, button: true, subTitle: "Real-estate Editing", btnText: "Buy Now​ Call Today​", title: "Revamp Your Online Game with Strategy-Driven Social Media Marketing!", paraArray: ["Elevate your online presence and make a splash in the digital world with Weeb Innovation's Strategy-Driven Social Media Marketing!Our approach goes beyond just posting content; we develop tailored strategies that align with your brand's goals and target audience. From creating engaging content to analyzing audience insights and optimizing ad campaigns, we ensure that your brand shines across social media platforms.", "With our strategy-driven approach, we'll help you revamp your online game and unlock new opportunities for growth and engagement. Let's collaborate to craft a social media strategy that drives results and propels your brand to success."]
        }} />
        < VideoSec />
        <Service1 data={{ imageDir: true, button: true, subTitle: "New Born baby", btnText: "Buy Now​ Call Today​", title: "Skyrocket Your Profits with the Magic of Affiliate Marketing!", paraArray: ["Transform your business and skyrocket your profits with the magic of Affiliate Marketing!At Weeb Innovation, we specialize in leveraging the power of affiliate marketing to drive revenue growth for your brand. Our strategic approach involves partnering with reputable affiliates who promote your products or services to their audience in exchange for a commission.", "With our proven affiliate marketing strategies, you can expand your reach, increase sales, and maximize your ROI. Let us help you tap into this lucrative revenue stream and take your business to new heights of success!"] }} />
        {/* <Service1 data={{ imageDir: false, button: true, subTitle: "Boudoir", btnText: "Buy Now​ Call Today​", title: "Top-tier 2D Infographic Video Production: Let Us Bring Your Ideas to Life!", paraArray: ["Experience top-tier 2D Infographic Video Production with Weeb Innovation: Where Your Ideas Come to Life!Our expert team transforms your concepts into engaging and informative 2D infographic videos that captivate your audience. Whether you're simplifying complex data or explaining intricate processes, our videos deliver your message with clarity and style.", "With meticulous attention to detail and a focus on visual storytelling, we create videos that leave a lasting impact. Let us help you elevate your brand and connect with your audience through the power of 2D infographic video production."] }} /> */}
        <div className="ped40"></div>

        < section className="Thirdservice samplework" >
          <div className="container">
            <div className="flex gap">
              <div className="col50">
                {" "}
                <ReactCompareImage
                  leftImage={"/assets/after.webp"}
                  rightImage={"/assets/before.webp"}
                />
              </div>
              <div className="col50">
                {" "}
                <ReactCompareImage
                  leftImage={"/assets/after.webp"}
                  rightImage={"/assets/before.webp"}
                />
              </div>
            </div>
          </div>
        </section>

        <Faq data={data} data_1={data_1} />

        <Cta />

      </Layouts >
    </>
  );
};

export default Video_edit;
