import Head from "next/head";
import Layouts from "@/components/Layouts";
import Banner from "@/components/Banner";
import AboutSection from "@/components/AboutSection";
import Service1 from "@/components/Service1";
import { Textmonial } from "@/components/Textmonial";
import VideoSec from "@/components/VideoSec";
import ChooseUs from "@/styles/ChooseUs";
import ImgSection from "@/components/ImgSection";
import ServiceHome from "@/components/ServiceHome";

// Image imported
// import aboutImg from "@/assets/about.webp";

export default function Home() {
  // console.log("Start");
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* font awesome */}
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
          integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer"
        />
      </Head>
      <Layouts>
        <Banner />
        <AboutSection
          data={{
            subTitle: "Who we are",
            title: "Meet the Power of Brilliant Editing!",
            description:
              "Refine Pixel is your creative alchemist! We offer dynamic editing services that transform your captured photos into visual masterpieces. We weave your work into wonders! Creating captivating narratives through your ideas.",
            btnName: "Read More",
            btnLink: "/about",
            image: "/assets/about.png",
          }}
        />

        <ServiceHome data={{
          imageDir: true, subTitle: "Image Editing", subContent: "Images Shine at Refine Pixels!", content: "Take your storytelling through images a notch up with our image editing services! We transform and add spark to every picture we come across. We help you exhibit tales with our creativity, precision and finesse.", button: "Read More", btnLink: "/services", aftimg: "./assets/ColourCorrection/3_a.jpg",
          befimg: "./assets/ColourCorrection/3_b.jpg",
        }} />
        <ServiceHome data={{
          imageDir: false, subTitle: "Web Design and Development", subContent: "Crafting And Revamping Websites For Maximum Impact!", content: "Embark on a journey of digital transformation as we meticulously craft and revamp websites to unleash their full potential for maximum impact. Our expert team combines cutting-edge design techniques with strategic insights to ensure your website not only looks stunning but also drives results", button: "Read More", btnLink: "/web_design_and_developement", 
          sideImg:"./assets/refinePixelImages/w1.jpg"
        }} />
        <VideoSec />
        <ServiceHome data={{
          imageDir: true, subTitle: "Video Editing", subContent: "Share Your Business Journey Through 2D Animation", content: "Our 2D animation service is more than just about creating visually stunning videos; it's about weaving narratives that forge strong connections with your audience. By merging strategic thinking with creativity, we produce animated content that not only grabs attention but also compels viewers to engage and act.", button: "Read More", btnLink: "/video_edit",sideImg:"./assets/refinePixelImages/v1.jpg"
        }} />
        <ServiceHome data={{
          imageDir: false, subTitle: "Graphic Designing", subContent: "Designing The Face Of Your Brand With Visual Identity Magic!", content: "Embark on a journey to sculpt the very essence of your brand's identity with our Visual Identity Magic service. Our expert team harnesses the power of design to craft captivating visuals that resonate with your audience, ensuring your brand stands out in a crowded digital landscape.", button: "Read More", btnLink: "/graphic_designing", sideImg:"./assets/refinePixelImages/g1.jpg"
        }} />
        <ChooseUs data={{ subTitle: "Why Choose Us?", title: "What Makes Us Different?", para: "Discover what sets us apart in the industry - from modern technology to a global approach. At Refine Pixel we redefine editing.", cards: [{ title: "Modern Technology", para: "Our state-of-the-art technology at Refine Pixel enhances and streamlines the editing process. It positions us at the industry's forefront." }, { title: "Global Perspective", para: "We have a client base all over the world. It encourages us to bring diverse and multicultural perspectives to our editing services." }, { title: "Competitive Pricing", para: "We offer our services at the best prices! Without compromising on the quality. We ensure our services are accessible to all, be it an individual or a business." }, { title: "24/7 Customer Support", para: "We offer 24/7 customer support and assistance. We address every client query, no matter when or where you're calling from." }] }} />
        <Textmonial />
        <ImgSection />
      </Layouts>
    </>
  );
}
