import React from "react";
import Head from "next/head";
import { Aboutbred } from "@/components/Aboutbred";
import Layouts from "@/components/Layouts";
import Service1 from "@/components/Service1";
import VideoSec from "@/components/VideoSec";
import Thirdservisec from "@/components/Thirdservisec";
import ReactCompareImage from "react-compare-image";
import Faq from "@/components/Faq";
import Cta from "@/components/Cta";

const WebDesignAndDevelopement = () => {
  const data = [
    {
      title: "What Is Included With Color Correction Services?",
      Description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
    {
      title: "What Is Included With Color Correction Services?",
      Description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
    {
      title: "What Is Included With Color Correction Services?",
      Description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
  ];
  const data_1 = [
    {
      title: "What Is Included With Color Correction Services?",
      Description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
    {
      title: "What Is Included With Color Correction Services?",
      Description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
    {
      title: "What Is Included With Color Correction Services?",
      Description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
  ];

  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layouts>
        <Aboutbred bread={"Web Design and Developement"} />
        <div className="ped40"></div>
        <Service1 data={{ imgPath: "./assets/refinePixelImages/s1.jpg",imageDir: true, button: true, subTitle: "Software Development", btnText: "Buy Now​ Call Today​", title: "Seamless Software Development: Error-Free Solutions, Every Time.", paraArray: ["Embark on a journey of seamless software development with our expert team. We specialize in crafting error-free solutions that meet your unique needs and exceed your expectations. From initial concept to final deployment, we prioritize quality at every step of the process to ensure a smooth and reliable experience for our clients."] }} />
        <Service1 data={{ imgPath: "./assets/refinePixelImages/s2.jpg",imageDir: false, button: true, subTitle: "Software Development", btnText: "Buy Now​ Call Today​", title: "Protect Your Assets: Implement IT Security Solutions for Risk Management.", paraArray: ["Shield your assets and fortify your digital infrastructure with our cutting-edge IT security solutions. We understand the importance of safeguarding your business from cyber threats, which is why we offer tailored risk management strategies to mitigate potential vulnerabilities. Our expert team employs a multi-layered approach."] }} />

        <Thirdservisec data={{ imgPath: "./assets/SectionImg.jpg",subTitle: "Software Development", title: "Unique API Integration: Your Solution, Your Style", paraArray: ["Unlock the full potential of your business with our bespoke API integration solutions. We understand that every business is unique, which is why we offer tailored integration services that align perfectly with your specific goals and requirements. Our expert team works closely with you to understand your business processes and objectives, ensuring seamless integration with your existing systems and technologies.", "Whether you're looking to streamline workflows, enhance productivity, or improve customer experiences, we're here to develop customized solutions that reflect your brand's style and identity. With our expertise and personalized approach, you can achieve your integration goals with confidence and efficiency."] }} />
        <Service1 data={{ imgPath: "./assets/refinePixelImages/s3.jpg",imageDir: true, button: true, subTitle: "Software Development", btnText: "Buy Now​ Call Today​", title: "Expertly Crafted Duda Platform Designs: Transform Your Website Experience", paraArray: ["Embark on a journey of digital transformation with our expertly crafted Duda platform designs. We specialize in creating stunning websites that not only showcase your brand but also provide an exceptional user experience. Our team combines creativity with technical expertise to tailor every aspect of your website to your unique needs and goals"] }} />
        <VideoSec />
        <Service1 data={{ imgPath: "./assets/refinePixelImages/s4.jpg",imageDir: true, button: true, subTitle: "Software Development", btnText: "Buy Now​ Call Today​", title: "Prompt App Maintenance & Support Services.", paraArray: ["Experience uninterrupted app performance with our prompt maintenance and support services. We understand the importance of keeping your app running smoothly, which is why we offer timely updates, bug fixes, and technical assistance to address any issues that may arise."] }} />
        <Service1 data={{ imgPath: "./assets/refinePixelImages/s5.jpg",imageDir: false, button: true, subTitle: "Software Development", btnText: "Buy Now​ Call Today​", title: "Customized App Development: Crafting Solutions to Fit Your Vision", paraArray: ["Immerse yourself in the realm of custom app development, where we meticulously craft solutions that align perfectly with your vision and objectives. Our expert team takes the time to understand your unique requirements, ensuring that every aspect of the app reflects your brand identity and meets your specific needs."] }} />

        <section className="Thirdservice samplework">
          <div className="container">
            <div className="flex gap">
              <div className="col50">
                {" "}
                <ReactCompareImage
                  leftImage={"/assets/after.webp"}
                  rightImage={"/assets/before.webp"}
                />
              </div>
              <div className="col50">
                {" "}
                <ReactCompareImage
                  leftImage={"/assets/after.webp"}
                  rightImage={"/assets/before.webp"}
                />
              </div>
            </div>
          </div>
        </section>
        {/* <section className="samplework1">
          <div className="container">
            <ReactCompareImage
              leftImage={"/assets/after.webp"}
              rightImage={"/assets/before.webp"}
            />
          </div>
        </section> */}

        <Faq data={data} data_1={data_1} />

        <Cta />

      </Layouts>
    </>
  );
};

export default WebDesignAndDevelopement;
